
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:1 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/CMake/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:1 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      生成启动时间为 2023/3/19 14:16:52。
      节点 1 上的项目“D:\\Documents\\projects\\2023华为软件精英挑战赛\\WindowsRelease\\SDK\\c++\\buidl\\CMakeFiles\\3.26.0-rc5\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdC.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      ClCompile:
        D:\\VS2017Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc141.pdb" /Gd /TC /analyze- /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        D:\\VS2017Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X86 /SAFESEH Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> D:\\Documents\\projects\\2023华为软件精英挑战赛\\WindowsRelease\\SDK\\c++\\buidl\\CMakeFiles\\3.26.0-rc5\\CompilerIdC\\.\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=D:\\VS2017Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\Hostx86\\x86\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdC.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate”执行 Touch 任务。
      已完成生成项目“D:\\Documents\\projects\\2023华为软件精英挑战赛\\WindowsRelease\\SDK\\c++\\buidl\\CMakeFiles\\3.26.0-rc5\\CompilerIdC\\CompilerIdC.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:01.95
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        D:/Documents/projects/2023华为软件精英挑战赛/WindowsRelease/SDK/c++/buidl/CMakeFiles/3.26.0-rc5/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/CMake/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:1 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
      版权所有(C) Microsoft Corporation。保留所有权利。
      
      生成启动时间为 2023/3/19 14:16:54。
      节点 1 上的项目“D:\\Documents\\projects\\2023华为软件精英挑战赛\\WindowsRelease\\SDK\\c++\\buidl\\CMakeFiles\\3.26.0-rc5\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)。
      PrepareForBuild:
        正在创建目录“Debug\\”。
        正在创建目录“Debug\\CompilerIdCXX.tlog\\”。
      InitializeBuildStatus:
        正在创建“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
      ClCompile:
        D:\\VS2017Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        D:\\VS2017Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X86 /SAFESEH Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> D:\\Documents\\projects\\2023华为软件精英挑战赛\\WindowsRelease\\SDK\\c++\\buidl\\CMakeFiles\\3.26.0-rc5\\CompilerIdCXX\\.\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=D:\\VS2017Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\Hostx86\\x86\\cl.exe
      FinalizeBuildStatus:
        正在删除文件“Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild”。
        正在对“Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate”执行 Touch 任务。
      已完成生成项目“D:\\Documents\\projects\\2023华为软件精英挑战赛\\WindowsRelease\\SDK\\c++\\buidl\\CMakeFiles\\3.26.0-rc5\\CompilerIdCXX\\CompilerIdCXX.vcxproj”(默认目标)的操作。
      
      已成功生成。
          0 个警告
          0 个错误
      
      已用时间 00:00:00.77
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        D:/Documents/projects/2023华为软件精英挑战赛/WindowsRelease/SDK/c++/buidl/CMakeFiles/3.26.0-rc5/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/CMake/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:1 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/Documents/projects/2023\u534e\u4e3a\u8f6f\u4ef6\u7cbe\u82f1\u6311\u6218\u8d5b/WindowsRelease/SDK/c++/buidl/CMakeFiles/CMakeScratch/TryCompile-ckcy18"
      binary: "D:/Documents/projects/2023\u534e\u4e3a\u8f6f\u4ef6\u7cbe\u82f1\u6311\u6218\u8d5b/WindowsRelease/SDK/c++/buidl/CMakeFiles/CMakeScratch/TryCompile-ckcy18"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: D:/Documents/projects/2023华为软件精英挑战赛/WindowsRelease/SDK/c++/buidl/CMakeFiles/CMakeScratch/TryCompile-ckcy18
        
        Run Build Command(s):D:/VS2017Community/MSBuild/15.0/Bin/MSBuild.exe cmTC_9b2f8.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=15.0 /v:n && 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
        版权所有(C) Microsoft Corporation。保留所有权利。
        
        生成启动时间为 2023/3/19 14:16:55。
        节点 1 上的项目“D:\\Documents\\projects\\2023华为软件精英挑战赛\\WindowsRelease\\SDK\\c++\\buidl\\CMakeFiles\\CMakeScratch\\TryCompile-ckcy18\\cmTC_9b2f8.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_9b2f8.dir\\Debug\\”。
          正在创建目录“D:\\Documents\\projects\\2023华为软件精英挑战赛\\WindowsRelease\\SDK\\c++\\buidl\\CMakeFiles\\CMakeScratch\\TryCompile-ckcy18\\Debug\\”。
          正在创建目录“cmTC_9b2f8.dir\\Debug\\cmTC_9b2f8.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_9b2f8.dir\\Debug\\cmTC_9b2f8.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        ClCompile:
          D:\\VS2017Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_9b2f8.dir\\Debug\\\\" /Fd"cmTC_9b2f8.dir\\Debug\\vc141.pdb" /Gd /TC /analyze- /errorReport:queue "D:\\CMake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27049 版
          版权所有(C) Microsoft Corporation。保留所有权利。
          
          cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_9b2f8.dir\\Debug\\\\" /Fd"cmTC_9b2f8.dir\\Debug\\vc141.pdb" /Gd /TC /analyze- /errorReport:queue "D:\\CMake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          CMakeCCompilerABI.c
          
        Link:
          D:\\VS2017Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\Documents\\projects\\2023华为软件精英挑战赛\\WindowsRelease\\SDK\\c++\\buidl\\CMakeFiles\\CMakeScratch\\TryCompile-ckcy18\\Debug\\cmTC_9b2f8.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Documents/projects/2023华为软件精英挑战赛/WindowsRelease/SDK/c++/buidl/CMakeFiles/CMakeScratch/TryCompile-ckcy18/Debug/cmTC_9b2f8.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Documents/projects/2023华为软件精英挑战赛/WindowsRelease/SDK/c++/buidl/CMakeFiles/CMakeScratch/TryCompile-ckcy18/Debug/cmTC_9b2f8.lib" /MACHINE:X86 /SAFESEH  /machine:X86 cmTC_9b2f8.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_9b2f8.vcxproj -> D:\\Documents\\projects\\2023华为软件精英挑战赛\\WindowsRelease\\SDK\\c++\\buidl\\CMakeFiles\\CMakeScratch\\TryCompile-ckcy18\\Debug\\cmTC_9b2f8.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_9b2f8.dir\\Debug\\cmTC_9b2f8.tlog\\unsuccessfulbuild”。
          正在对“cmTC_9b2f8.dir\\Debug\\cmTC_9b2f8.tlog\\cmTC_9b2f8.lastbuildstate”执行 Touch 任务。
        已完成生成项目“D:\\Documents\\projects\\2023华为软件精英挑战赛\\WindowsRelease\\SDK\\c++\\buidl\\CMakeFiles\\CMakeScratch\\TryCompile-ckcy18\\cmTC_9b2f8.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:01.04
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/CMake/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:1 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/Documents/projects/2023\u534e\u4e3a\u8f6f\u4ef6\u7cbe\u82f1\u6311\u6218\u8d5b/WindowsRelease/SDK/c++/buidl/CMakeFiles/CMakeScratch/TryCompile-5vr3s2"
      binary: "D:/Documents/projects/2023\u534e\u4e3a\u8f6f\u4ef6\u7cbe\u82f1\u6311\u6218\u8d5b/WindowsRelease/SDK/c++/buidl/CMakeFiles/CMakeScratch/TryCompile-5vr3s2"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: D:/Documents/projects/2023华为软件精英挑战赛/WindowsRelease/SDK/c++/buidl/CMakeFiles/CMakeScratch/TryCompile-5vr3s2
        
        Run Build Command(s):D:/VS2017Community/MSBuild/15.0/Bin/MSBuild.exe cmTC_30b76.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=15.0 /v:n && 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
        版权所有(C) Microsoft Corporation。保留所有权利。
        
        生成启动时间为 2023/3/19 14:16:57。
        节点 1 上的项目“D:\\Documents\\projects\\2023华为软件精英挑战赛\\WindowsRelease\\SDK\\c++\\buidl\\CMakeFiles\\CMakeScratch\\TryCompile-5vr3s2\\cmTC_30b76.vcxproj”(默认目标)。
        PrepareForBuild:
          正在创建目录“cmTC_30b76.dir\\Debug\\”。
          正在创建目录“D:\\Documents\\projects\\2023华为软件精英挑战赛\\WindowsRelease\\SDK\\c++\\buidl\\CMakeFiles\\CMakeScratch\\TryCompile-5vr3s2\\Debug\\”。
          正在创建目录“cmTC_30b76.dir\\Debug\\cmTC_30b76.tlog\\”。
        InitializeBuildStatus:
          正在创建“cmTC_30b76.dir\\Debug\\cmTC_30b76.tlog\\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
        ClCompile:
          D:\\VS2017Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_30b76.dir\\Debug\\\\" /Fd"cmTC_30b76.dir\\Debug\\vc141.pdb" /Gd /TP /analyze- /errorReport:queue "D:\\CMake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27049 版
          版权所有(C) Microsoft Corporation。保留所有权利。
          
          cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_30b76.dir\\Debug\\\\" /Fd"cmTC_30b76.dir\\Debug\\vc141.pdb" /Gd /TP /analyze- /errorReport:queue "D:\\CMake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          CMakeCXXCompilerABI.cpp
          
        Link:
          D:\\VS2017Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\Documents\\projects\\2023华为软件精英挑战赛\\WindowsRelease\\SDK\\c++\\buidl\\CMakeFiles\\CMakeScratch\\TryCompile-5vr3s2\\Debug\\cmTC_30b76.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Documents/projects/2023华为软件精英挑战赛/WindowsRelease/SDK/c++/buidl/CMakeFiles/CMakeScratch/TryCompile-5vr3s2/Debug/cmTC_30b76.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Documents/projects/2023华为软件精英挑战赛/WindowsRelease/SDK/c++/buidl/CMakeFiles/CMakeScratch/TryCompile-5vr3s2/Debug/cmTC_30b76.lib" /MACHINE:X86 /SAFESEH  /machine:X86 cmTC_30b76.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_30b76.vcxproj -> D:\\Documents\\projects\\2023华为软件精英挑战赛\\WindowsRelease\\SDK\\c++\\buidl\\CMakeFiles\\CMakeScratch\\TryCompile-5vr3s2\\Debug\\cmTC_30b76.exe
        FinalizeBuildStatus:
          正在删除文件“cmTC_30b76.dir\\Debug\\cmTC_30b76.tlog\\unsuccessfulbuild”。
          正在对“cmTC_30b76.dir\\Debug\\cmTC_30b76.tlog\\cmTC_30b76.lastbuildstate”执行 Touch 任务。
        已完成生成项目“D:\\Documents\\projects\\2023华为软件精英挑战赛\\WindowsRelease\\SDK\\c++\\buidl\\CMakeFiles\\CMakeScratch\\TryCompile-5vr3s2\\cmTC_30b76.vcxproj”(默认目标)的操作。
        
        已成功生成。
            0 个警告
            0 个错误
        
        已用时间 00:00:00.81
        
      exitCode: 0
...
